- name: Hello
  hosts: all
  tasks: 
    - name: Message
      debug: 
        msg: "Hello" 
    
    - name: Facts
      ansible.builtin.debug: 
         msg: System {{inventory_hostname}} at {{ ansible_default_ipv4.gateway }}
        

    - name: print all known facts
      ansible.builtin.debug:
        msg: hostvars[inventory_hostname]
        verbosity: 4
      when: ansible_defualt_ipv4.gateway is defined