- name: hello Play
  hosts: raspberrypies
  tasks: 
       - name: hello module
         hello: 
         register: result
       
       - name: change version
         version_change:  
           version_no: 1.1.1
           version_name: "initial version"
           version_unchanged: "not updated"
         register: result
       - debug: var=result