- name: hello Play
  hosts: raspberrypies
  tasks: 
       - name: hello module
         hello: 
         register: result
       
       - name: Test that version number can be incremented
         version_change: 
         version_name: "Initial"
         version_no:  1.1.1 
         unchanged_value: "Demo"
         register: result
       - debug: var=result  